# Generated by Django 5.2.8 on 2025-11-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Opportunita'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.IntegerField(default=0, help_text='Probabilita in %'),
        ),
    ]
