# Generated by Django 5.2.8 on 2025-11-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_opportunity_number_alter_opportunity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
