# Generated by Django 5.2.8 on 2025-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoice_number_alter_offer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
