# Generated by Django 5.2.8 on 2025-11-24 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_saleorder_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='expected_close_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='expected_value',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='probability',
        ),
        migrations.AddField(
            model_name='offer',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='inserted_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='invoicing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
