# Generated by Django 5.2.8 on 2025-11-24 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_opportunity_expected_close_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Ragione Sociale'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='inserted_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
