# Generated by Django 5.2.8 on 2025-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_client_name_alter_opportunity_inserted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
