# Generated by Django 5.2.8 on 2025-11-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_offer_description_opportunity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='opportunities/'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='orders/'),
        ),
    ]
